#  my first programe 
print('hello world ')
print (5)
print("my name is ramesh",81)
print (12*25)
# lecture number 5
print( "my name is ramesh kumar \" and my university name is future\" ExceptionGroup")
print( "you are my best friend in my life ")
print( "you are my best friend in my life ")
print( "you are my best friend in my life ")
# print( "you are my best friend in my life 
# print( "you are my best friend in my life ")
print("hey",4,6, sep="~", end="9858\9")
print("ramesh kumar ")
#  lecture number 6 what is variable and data type \\\
a= 2
print (a)
b=4
print(b)
print(a+b)
print("the type of a is ",type(a))
print("the type of b is ",type(b)) 
c=2.3
print(c)
d=2.33
print(d,type (d))
print(c+d)
e=2+5j 
print(e )
print(d+e)
print("type of e ",type(e))
# lecture number 7
# make a calculator 
print(5+2)
print(5-2)
print(5*2)
print(5/2)
print(12%5)
print(2%40)
print(25//5)
print(2**5)
print(2&3)
print(4^5)
print(62++6)
# lecture number is 8 make a calculator \\\ type casting 
c=22
v=44
print("the value of " ,c, " + ",44,"is:",c+v )
print("the value of " ,c, " - ",44,"is:",c+v )
print("the value of " ,c, " * ",44,"is:",c+v )
print("the value of " ,c, " / ",44,"is:",c+v )
print("the value of " ,c, " // ",44,"is:",c+v )
print("the value of " ,c, " & ",44,"is:",c+v )
print("the value of " ,c, " % ",44,"is:",c+v )
# lacture no 9 typecasting 
s ="3","ramesh"
x="5","kumar"
print(s+x)
e =5.44848
q= 5
print(int(e)+ int (q))
# m=float(input("enter the value 1:"))
# n =float(input("enter the value2:5"))
# print(m+n)
# x=eval(input("enter the value :1"))
# z=eval(input("enter the value :2"))
# print(x+z)
# print() 
# f=str(input("enter the value :1"))
# l=str(input("enter the value :2"))
# print(f+l)
# print()
# print("q",type(q))
# print("e",type(e))
# lacture no 10  taking input usre 
# a= input("enter the anyname ")
# print("my name is",a) 
# g= input("enter the number1 ")
# h=input("enter the number2")
# print(g+h)
# print(int(g)+int(h))
# lacture no 11  concept of the string 
A="ramesh kumar"
B='ajeet singh'
ramesh='''(Bitcoin recorded another remarkable price performance in the past week, gaining by 19.16% according to data from CoinMarketCap. The crypto market leader established a new all-time high at $93,434 on Wednesday, as odds of achieving a six-figure market price by year’s end are now higher than before. 

Amidst the current market euphoria, CryptoQuant analyst Amr Taha has shared some market insights that may indicate an impending price fall.

Bitcoin Enters Profit-Taking Zone – Sell Or HODL?

In a Quicktake post on Friday, Amr Taha stated many investors may be preparing for a cash-out as the Bitcoin MVRV ratio reached 2.64. Generally, the Market Value to Realized Value is a trading indicator used to measure whether an asset is overvalued or undervalued or to identify market tops or bottoms.

# # However, Ama Taha further explains that Bitcoin may sometimes only form a major market top when the MVRV ratio reaches as high as 4. Therefore, at 2.64, the premier cryptocurrency may still sustain its current upward price trajectory, if bullish market momentum persists. The analyst advises that investors monitor the MVRV ratio as a rise towards 3 would signal the potential for further price gains while a decline to a range of 1.5-2 indicates a local market top is forming.

Short-Term Holders Realized Cap Hits $30 Billion

In addition to Bitcoin’s alarming MVRV ratio, Taha also noted that short-term holders have now accumulated a realized market cap of over $30 billion, a level last observed in March 2024. The CryptoQuant analyst stated Bitcoin has historically undergone significant price corrections whenever the STH realized cap reached similar levels, signaling another warning for investors of a potential price dip.

At the time of writing, Bitcoin is trading at $91,738 with a 3.97% gain in the past 24 hours. However, the asset’s trading volume is down by 7.42% and is valued at $80.73 billion.)'''
print(ramesh )
print("A"+"B")
# concept of the Espace 
print('what\'s the name of child?' )
print("ramesh go to the home,\"and start the tv and see the south indian movie.\"")
print("my date of birth.\nindia is a madarchod cuntry .")
print("hello all the student.\t welcome to the class.")
print("hello basanti'\f chal nikal ja ghar? ")
print()
str="my  name is chutiya "
print(str[0])
print(str[1])
print(str[2])
print(str[3])
print(str[4])
print(str[5])
print(str[1:5])
print([len(str)])
print(str* 3)
print(str+"madarchod")
print(str[5])
print(str[1-3])
print(str[1-2-4])
# inpuut, operation and concatenation \\\\\
# naam= input ("what,s your name? ")
# age =input ("enter your age:")
# print(naam+",you are chutiya " + age +"20 year old ")
# print ("tou are crezy " +"your are so chutiya ")
print('ajeet'*4 ,"ramesh"+"kumar")
ram='''my name is ram i  from india i want a job in your compny . thank you  sir.?  and  tuple is similer to the list,..
counting number is 87791833867 and 878647544165451566454844548 ,.? good morning sir/ new to this edition 
importent note .., it difined one by one now 
(1): additional  programing examples
(2): case  studies is the biogaraphy ..?
(3) "    " teri ma ka bhosda 
 '''
kunal =("my name is ,. mowngli lenegd of the jungle ")
print(len(ram))
print(ram.upper())
print(ram.capitalize())
print(ram.title())
print(ram.istitle())
print(ram.islower())
print(ram.upper())
print(ram.swapcase())
print(kunal.swapcase())
print(kunal.title())
# condition statement  if ,ifelse ,elif ,nested if ,\\\\
a= int(input("enter the any number"))
if a % 2 ==0:
    print(a,"even number") 
else:
    print(a,"odd number")
print()
per = int(input("enter the value "))
if per>=34:
    print("first div ")
elif per >=40:
    print("second div ")
elif per>=50:
    print("3rd div ")
elif per>=90:
    print("4th div ")
else:
    print("fail") 
print()
# write a program to determine the character  entered by the user ...
char =input(" press any key ")
if (char.isalpha()):
    print("char")
    print(" the user has entered a character ")
if (char.isdigit()):
    print(" the user has  enterd a digit ")
    print()
    # 
    # write a program for a positive and negative number ...
num=float(input("enter a number "))
if num>=0:
    if num==0:
        print("zero")
    else:
        print("positive  number")
print("negative number ")
    
    
        # write a program to find a larger of to number \\
A=int(input("enter the value of  A :"))
B= int(input("enter the value of  B :"))
if(A>B):
            large =A
else:
            large =B
            print("large=",large) 
            print()
# 
# match statment concept \\ 
x =int(input("enter the value x: "))
match x:   
  case 0:
   print("case is zero")
  case 4:
   print("case is 4")
   print()

Name ="ramesh "
for i in  ramesh:
     print(i)
# write a program using for loop to calculate  the average of first n natural numbers ..
n=int(input("enter the any number n : "))
avg =0.0
s=0
for i in range(1,n+1):
    s= s+i 
    avg=s/i
    print("the sum of  first ",n,"natural number is ",s)
    print("the average of the first",n,"natural number is ",avg )

# write a program to calculate the sum of cubes of numbers fromm 1-n 
n= int(input("enter the value of n :"))
s = 0
for i in range(1,1+n):
    a=i**3
    s=s+a
    print("teh sum of cubes is ",s)
print ("hello bhai")